stronka/coffee_finder/urls.py
from django.urls import path
from . import views

app_name = "coffee_finder"

urlpatterns = [
    path("",views.index,name="index"),
    path("signup/",views.signup,name="signup"),
    path("login/",views.login_handler,name="login"),
    path("favourites_handler/",views.js_favourites_handler,name="favourites_request"),
    path("favourites/favourites_delete/",views.js_favourites_delete,name="favourites_delete"),
    path("favourites/",views.favourites,name="favourites"),
    path("favourites/<place>/",views.place,name="place")
]

stronka/stronka/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("coffee_finder/",include("coffee_finder.urls")),
    path('admin/', admin.site.urls),
]

stronka/coffee_finder/models.py
from django.db import models
from django.contrib.auth.models import User
from django_mysql.models import JSONField
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    location = models.CharField(max_length=100,default="Warsaw")
    
class Places(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    my_places = JSONField()

class Favourites(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    my_favourites = JSONField()

class Rejected(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)
    my_rejected = JSONField()

stronka/coffee_finder/views.py
import requests
import json
import time
import threading
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.template.defaulttags import register
from .models import Profile, Places, Favourites, Rejected

api_key = "AIzaSyA10sWJ6IOVGEIyHuygj8tIBDKr8RjDyEU"

def ParsedCafeData(info):
    formatted_address = info["formatted_address"]
    name = info["name"]
    place_id = info["place_id"]
    if "opening_hours" in info and "open_now" in info["opening_hours"]:
        isopen = info["opening_hours"]
        isopen = isopen["open_now"]
    else:
        isopen = "No data"

    if "photos" in info:
        photo = info["photos"]
        photo = photo[0]
        photo = photo["photo_reference"]
        photo = "https://maps.googleapis.com/maps/api/place/photo?maxheight=800&photoreference="+photo+"&key="+api_key
    else:
        photo = "https://maps.googleapis.com/maps/api/place/photo?maxheight=800&photoreference=CmRaAAAAZOkFJe830BVBm2Glk2rOxwMSnEtkR5PO1z1_VSMmxiPbdQkWLFzVXX9enkSdqECGHVDM4Qxt4bQIrfEajTi6NNsQVtwzskFXGT_pgxi6kH9sF8yr7JPQfJxSCW7H0xWQEhAVC39nIeFLkTiTxSaLoMydGhT14LkzvSTbfg2F74__oiET-t8ltA&key=AIzaSyA10sWJ6IOVGEIyHuygj8tIBDKr8RjDyEU"
    return {"name":name,"formatted_address":formatted_address,"photo":photo,"isopen":isopen,"place_id":place_id}

def NextPage(response,location,profile,username,request):
    while "next_page_token" in response:
        time.sleep(1.51)
        next_page_token = response["next_page_token"]
        response = requests.post("https://maps.googleapis.com/maps/api/place/textsearch/json?query="+location+"&type=cafe&pagetoken="+next_page_token+"&key="+api_key)
        response = json.loads(response.text)
        if response["status"] == "OK":
            info = response["results"]
            for i in range(len(info)):
                Places.objects.create(profile=profile,my_places=info[i])
        else:
            return render(request,"coffee_finder/index.html",{"name":"NO DATA","location":location,"username":username,"formatted_address":"NO DATA","photo":"NO PHOTO","isopen":"NO DATA"})

def index(request):
    if request.user.is_anonymous:
        return HttpResponseRedirect(reverse("coffee_finder:login"))

    # INFO BAR
    username = request.user
    profile = Profile.objects.filter(user=request.user).get()
    location = profile.location
    # Jak nie ma propozycji to ładuje nowe
    if len(profile.places_set.all())==0:
        response = requests.post("https://maps.googleapis.com/maps/api/place/textsearch/json?query="+location+"&type=cafe&key="+api_key)
        response = json.loads(response.text)
        if response["status"] == "OK":
            info = response["results"]
            for i in range(len(info)):
                Places.objects.create(profile=profile,my_places=info[i])
        else:
            return render(request,"coffee_finder/index.html",{"name":"NO DATA","location":location,"username":username,"formatted_address":"NO DATA","photo":"NO PHOTO","isopen":"NO DATA"})

        stuff = threading.Thread(target=NextPage, name="\n", args=[response,location,profile,username,request])
        stuff.start()
    data = ParsedCafeData(profile.places_set.all()[0].my_places)

    if request.method == "POST":
        previous_location = location
        location = request.POST.get("location")
        user = request.user
        Profile.objects.filter(user=user).update(user=user,location=location)

        response = requests.post("https://maps.googleapis.com/maps/api/place/textsearch/json?query="+location+"&type=cafe&key="+api_key)
        response = json.loads(response.text)
        if response["status"] == "OK":
            profile.places_set.filter(profile=profile).delete()
            info = response["results"]
            for i in range(len(info)):
                Places.objects.create(profile=profile,my_places=info[i])
            stuff = threading.Thread(target=NextPage, name="\n", args=[response,location,profile,username,request])
            stuff.start()
        else:
            Profile.objects.filter(user=user).update(user=user,location=previous_location)
            location = previous_location
            return render(request,"coffee_finder/index.html",{"name":data["name"],"location":location,"username":username,"formatted_address":data["formatted_address"],"photo":data["photo"],"isopen":data["isopen"]})

    return render(request,"coffee_finder/index.html",{"name":data["name"],"location":location,"username":username,"formatted_address":data["formatted_address"],"photo":data["photo"],"isopen":data["isopen"]})

@register.filter
def get_item(dict,key):
    return dict.get(key)

def favourites(request):
    if request.user.is_anonymous:
        return HttpResponseRedirect(reverse("coffee_finder:login"))
    profile = Profile.objects.filter(user=request.user).get()
    username = request.user
    location = profile.location
    favourites = []

    for object in profile.favourites_set.all():
        favourites.append(ParsedCafeData(object.my_favourites))

    return render(request,"coffee_finder/favourites.html",{"username":username,"location":location,"favourites":favourites})

def place(request, place):
    if request.user.is_anonymous:
        return HttpResponseRedirect(reverse("coffee_finder:login"))
    profile = Profile.objects.filter(user=request.user).get()
    username = request.user
    location = profile.location
    name = place
    for object in profile.favourites_set.all():
        if object.my_favourites["name"] == name:
            if "photos" in object.my_favourites:
                photo = object.my_favourites["photos"]
                photo = photo[0]
                photo = photo["photo_reference"]
                photo = "https://maps.googleapis.com/maps/api/place/photo?maxheight=800&photoreference="+photo+"&key="+api_key
            else:
                photo = "https://maps.googleapis.com/maps/api/place/photo?maxheight=800&photoreference=CmRaAAAAZOkFJe830BVBm2Glk2rOxwMSnEtkR5PO1z1_VSMmxiPbdQkWLFzVXX9enkSdqECGHVDM4Qxt4bQIrfEajTi6NNsQVtwzskFXGT_pgxi6kH9sF8yr7JPQfJxSCW7H0xWQEhAVC39nIeFLkTiTxSaLoMydGhT14LkzvSTbfg2F74__oiET-t8ltA&key=AIzaSyA10sWJ6IOVGEIyHuygj8tIBDKr8RjDyEU"
            details = requests.post("https://maps.googleapis.com/maps/api/place/details/json?place_id="+object.my_favourites["place_id"]+"&key="+api_key)
            details = json.loads(details.text)
            details = details["result"]
            rating = object.my_favourites["rating"]
            if "opening_hours" in details:
                schedule = details["opening_hours"]
                isopen = schedule["open_now"]
                schedule = schedule["weekday_text"]
            else:
                schedule = ["No data"]
                isopen = "No data"
            if "reviews" in details:
                review = details["reviews"]
                review = review[0]
                map = "https://www.google.com/maps/embed/v1/place?q=place_id:"+object.my_favourites["place_id"]+"&key="+api_key
                return render(request, "coffee_finder/place.html",{"object":object.my_favourites,"details":details,"username":username,"location":location,"isopen":isopen,"photo":photo,"review":review,"schedule":schedule,"map":map})
            else:
                map = "https://www.google.com/maps/embed/v1/place?q=place_id:"+object.my_favourites["place_id"]+"&key="+api_key
                return render(request, "coffee_finder/place.html",{"object":object.my_favourites,"details":details,"username":username,"location":location,"isopen":isopen,"photo":photo,"review":"","schedule":schedule,"map":map})

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username,password=raw_password)
            login(request,user)
            user = request.user
            profile = Profile(user=user)
            profile.save()
            return HttpResponseRedirect(reverse("coffee_finder:index"))
    else:
        form = UserCreationForm()
    return render(request,"coffee_finder/signup.html",{"form":form})

def login_handler(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username,password=password)
        if user:
            login(request,user)
            return HttpResponseRedirect(reverse("coffee_finder:index"))
        else:
            return HttpResponse("Wrong data")
    return render(request, "coffee_finder/login.html")

def js_favourites_delete(request):
    id = request.GET["id"]
    profile = Profile.objects.filter(user=request.user).get()
    if request.method == "GET" :
        favourites = profile.favourites_set.all()
        for favourite in favourites :
            if favourite.my_favourites["place_id"] == id :
                favourite.delete()
        # Favourites.objects.delete(profile=profile, )
        return HttpResponse("It works")

def js_favourites_handler(request):
    profile = Profile.objects.filter(user=request.user).get()
    if request.method == "GET":
        # handle right swipe
        if request.GET["direction"] == "right" :
            right = profile.places_set.all()[0]
            if len(profile.favourites_set.all())>0:
                for i in range (len(profile.favourites_set.all())):
                    if (ParsedCafeData(profile.places_set.all()[0].my_places))["name"] == (ParsedCafeData(profile.favourites_set.all()[i].my_favourites))["name"]:
                        right.delete()

stronka/coffee_finder/templates/coffee_finder/favourites.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- <script src="{% static "coffee_finder/favourites.js" %}"></script> -->
    <link rel="shortcut icon" type="image/png" href="{% static 'coffee_finder/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "coffee_finder/favourites.css" %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>Coffee Finder Favourites Page</title>
  </head>
  <body class="body">
      <div class="menu">
        <div class="menu1">
          <h1>Favourites</h1>
        </div>
        <div class="menu2">
          <div class="username">
            <div><strong>Username: </strong>{{ username }}</div>
            <div><strong>Location: </strong>{{ location }}</div>
          </div>
          <div onclick="location.href='{% url "coffee_finder:index" %}';" class="button" style="cursor: pointer;">
            Main Page
          </div>
        </div>
      </div>
    <div class="body1">
      <div class="container">
        {% csrf_token %}
        {% for favourite in favourites %}
        <div class="content1" id="{{ favourite.place_id }}">
          <div id="{{ favourite.name }}"><img onclick="clicked(`{{ favourite.place_id }}`);" class="icon" src="{% static "coffee_finder/x-square.svg" %}" alt=""></div>
          <div onclick="location.href='{% url "coffee_finder:place" favourite.name %}';" class="content">
            <div class="photowrap">
              <img class="photo" src="{{ favourite.photo }}" alt="coffee_finder/kahawa.jpg">

            </div>
            <div class="description">
              <div><strong>Name: </strong id="name">{{ favourite.name }}</div>
              <div><strong>Adress: </strong>{{ favourite.formatted_address }}</div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <script src="{% static "coffee_finder/favourites.js" %}"></script>
  </body>
</html>

stronka/coffee_finder/templates/coffee_finder/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'coffee_finder/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "coffee_finder/master.css" %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>Find yourself in coffee</title>
  </head>
  <body class="body">
    <div class="body1">
      <div class="menu">
        <div class="menu1">
          <div class="headers">
            <h1 class="header1">Coffee Finder</h1>
            <h3 class="header2">Find yourself in coffee</h3>
          </div>
          <div class="input">
            {% block content %}
            <form method="POST">
                {% csrf_token %}
                <label for="location"><strong>Location:</strong></label>
                <input type="text" name="location">
                <button type="submit" name="send">Send</button>
            </form>
            {% endblock %}
          </div>
        </div>
        <div class="username">
          <div><strong>Username: </strong>{{ username }}</div>
          <div><strong>Location: </strong>{{ location }}</div>
          <div onclick="location.href='{% url "coffee_finder:favourites" %}';" class="button" style="cursor: pointer;">Favourites</div>
        </div>
      </div>
      <div class="body2">
        <div class="grinder">
          <span id="grind">GRIND IT!</span>
          <img id="grinder" src="{% static "coffee_finder/mill.svg" %}" alt="">
        </div>
        <div class="content grow" id="content">
          <div class="photowrap">
            <div class="left" id="left" onclick="mouseClickLeft()"></div>
            <div class="right" id="right" onclick="mouseClickRight()"></div>
            <div class="photo">
              <img class="image" src="{{ photo }}" alt="{% static "coffee_finder/kahawa.jpg" %}">
              <!-- <div class="image">{{ photo }}</div> -->
            </div>
          </div>
          <div class="description">
            <div><strong>Name: </strong><span id="name">{{ name }}</span></div>
            <div><strong>Address: </strong><span id="formatted_address">{{ formatted_address }}</span></div>
            <div><strong>Is serving coffee now: </strong><span id="isopen">{{ isopen }}</span></div>
          </div>
        </div>
        <div class="bean">
          <img id="bean" src="{% static "coffee_finder/seed.svg" %}" alt="">
          <span id="save">SAVE IT!</span>
        </div>
      </div>
    </div>
    <div class="footer">Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
    <script src="{% static "coffee_finder/swipe.js"%}"></script>
  </body>
</html>

stronka/coffee_finder/templates/coffee_finder/login.html
{% extends 'coffee_finder/signup.html' %}
{% load static %}
{% block content %}
<head>
  <link rel="shortcut icon" type="image/png" href="{% static 'coffee_finder/favicon.ico' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static "coffee_finder/login.css" %}">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
  <title>Coffee Finder Login Page</title>
</head>
<body class="body">
  <div class="wrap">
    <div class="login">
      <h2 class="header">LOGIN</h2>
        <form method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username">
            <label for="password">Password:</label>
            <input type="password" name="password">
            <input type="submit" name="" value="login">
        </form>
        <div class="">
          <a href="{% url "coffee_finder:signup" %}">Redirect to sign up page</a>
        </div>
    </div>
  </div>
</body>
{% endblock %}

stronka/coffee_finder/templates/coffee_finder/place.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="shortcut icon" type="image/png" href="{% static 'coffee_finder/favicon.ico' %}"/>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static "coffee_finder/place.css" %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <title>{{ object.name }}</title>
  </head>
  <body>
    <div class="menu">
      <div class="menu1">
        <h1>{{ object.name }}</h1>
      </div>
      <div class="menu2">
        <div class="username">
          <div><strong>Username: </strong>{{ username }}</div>
          <div><strong>Location: </strong>{{ location }}</div>
        </div>
        <div onclick="location.href='{% url "coffee_finder:favourites" %}';" class="button" style="cursor: pointer;">
          Favourites
        </div>
      </div>
    </div>
    <div class="content">
      <div class="photowrap">
        <div class="photo">
          <img class="image" src="{{ photo }}" alt="{% static "coffee_finder/kahawa.jpg" %}">
        </div>
      </div>
      <div class="description">
        <div><strong>Name: </strong><span id="name">{{ object.name }}</span></div>
        <div><strong>Address: </strong><span id="formatted_address">{{ object.formatted_address }}</span></div>
        <div><strong>Rating: </strong><span>{{ object.rating }}</span></div>
        <div><strong>Schedule: </strong>{% for hour in schedule %}<div>{{ hour }}</div>{% endfor %}</div>
        <div><strong>Review: </strong><span>{{ review.text }}</span></div>
        <div><strong>Review's author: </strong><span>{{ review.author_name }}</span>
        <div><strong>Is serving coffee now:  </strong><span id="isopen">{{ isopen }}</span></div>
        <div class="map">
        <iframe width="450" height="400" frameborder="0" style="border:0"
        src={{ map }} allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </body>
</html>

stronka/coffee_finder/templates/coffee_finder/signup.html
{% load static %}
{% block content %}
<head>
  <link rel="shortcut icon" type="image/png" href="{% static 'coffee_finder/favicon.ico' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static "coffee_finder/login.css" %}">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
  <title>Coffee Finder Signup Page</title>
</head>
<body class="body">
  <div class="wrap">
    <div class="login">
      <h2 class="header">SIGN UP</h2>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <small>{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <button type="submit" class="button">Sign up</button>
      </form>
    </div>
  </div>
</body>
{% endblock %}

stronka/coffee_finder/templates/coffee_finder/test.html
{% block content %}
<form method="POST">
    {% csrf_token %}
    <link rel="shortcut icon" type="image/png" href="{% static 'coffee_finder/favicon.ico' %}"/>
    <label for="location">Location:</label>
    <input type="text" name="location">
    <input type="submit">
</form>
{% endblock %}